name: python-analytics-ich
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pmdarima
  - prophet
  - openpyxl
  - xlrd
